# This is a basic workflow to help you get started with Actions

name: Automated data update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '*/60 */22 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install dependencies
      run: yarn
   # Runs a single command using the runners shell
    - name: download data
      run: yarn download
  # Runs a single command using the runners shell
    - name: download data
      run: yarn download
  # Runs a single command using the runners shell
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: automatically data updated

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event
        branch: ${{ github.head_ref }}

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: github-bot
        commit_user_email: github-bot@auto.org
        commit_author: github-bot <actions@github.com>
